version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:16.3
    environment:
      POSTGRES_DB: "db-customer-transfer"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      TZ: "America/Sao_Paulo"
    ports:
      - "15433:5432"
    networks:
      - docker-network
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "marques.erick@outlook.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "True"
      TZ: "America/Sao_Paulo"
    ports:
      - "18080:80"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      TZ: "America/Sao_Paulo"
    ports:
      - "15673:15672"  # Porta para a interface de gerenciamento
      - "5673:5672"     # Porta padrão do RabbitMQ para conexões
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge
